# Generated by Django 4.1.7 on 2023-03-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='image_field',
            field=models.ImageField(null=True, upload_to='icons_app/static/images'),
        ),
    ]
