# Generated by Django 4.1.7 on 2023-03-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons_app', '0002_alter_pictures_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='image_field',
            field=models.ImageField(null=True, upload_to='static/icons_app/images'),
        ),
    ]
